---SUBQUERIES
--EQUAL(=)
SELECT ENAME,JOB,SAL,DEPTNO FROM EMP WHERE SAL =(SELECT MAX(SAL) FROM EMP);
SELECT ENAME,SAL,JOB,DEPTNO FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP);
SELECT ENAME,SAL,JOB,DEPTNO FROM EMP WHERE JOB =(SELECT JOB FROM EMP WHERE ENAME='SMITH' );
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='ALLEN') AND SAL>(SELECT SAL FROM EMP WHERE ENAME='MILLER');
SELECT ENAME,SAL,(SELECT AVG(SAL) FROM EMP) FROM EMP;
SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP);

--IN
SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE JOB IN(SELECT JOB FROM EMP WHERE ENAME IN('SMITH','BLAKE'));
SELECT DEPTNO, DNAME, LOC FROM DEPT WHERE DEPTNO IN(SELECT DISTINCT DEPTNO FROM EMP);
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE EMPNO IN(SELECT DISTINCT MGR FROM EMP WHERE MGR IS NOT NULL);
SELECT DEPTNO, DNAME, LOC FROM DEPT WHERE DEPTNO NOT IN(SELECT DISTINCT DEPTNO FROM EMP);
----EXISTS

SELECT ENAME, DEPTNO FROM EMP E WHERE EXISTS (SELECT * FROM DEPT D WHERE D.DEPTNO = E.DEPTNO);
SELECT DEPTNO, DNAME, LOC FROM DEPT D WHERE EXISTS(SELECT * FROM EMP WHERE DEPTNO=D.DEPTNO);
SELECT d.dname FROM dept d WHERE EXISTS ( SELECT DNAME FROM emp e WHERE e.deptno = d.deptno);
----NOT EXISTS
 SELECT DEPTNO, DNAME, LOC FROM DEPT D WHERE NOT EXISTS(SELECT * FROM EMP WHERE DEPTNO=D.DEPTNO);
 SELECT d.dname FROM dept d WHERE NOT EXISTS( SELECT DNAME FROM emp e WHERE e.deptno = d.deptno);
 SELECT ENAME, DEPTNO FROM EMP E WHERE NOT EXISTS (SELECT * FROM DEPT D WHERE D.DEPTNO = E.DEPTNO);

----Correlated Subquery
SELECT E1.ENAME,(SELECT COUNT(*) FROM EMP E2 WHERE E2.DEPTNO = E1.DEPTNO AND E2.EMPNO <> E1.EMPNO)AS COUNT FROM EMP E1;
SELECT ENAME, SAL, DEPTNO FROM EMP E WHERE SAL = (SELECT MAX(SAL)FROM EMP WHERE DEPTNO = E.DEPTNO);
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP E WHERE SAL>(SELECT AVG(SAL) FROM EMP WHERE DEPTNO = E.DEPTNO);
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP E WHERE 3>(SELECT COUNT(DISTINCT SAL) FROM EMP WHERE SAL>E.SAL);
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP E WHERE 2=(SELECT COUNT(DISTINCT SAL) FROM EMP WHERE SAL>E.SAL);
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP E WHERE SAL=(SELECT MIN(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);






